export const FETCH_COFFEE_START = "FETCH_COFFEE_START";
export const FETCH_COFFEE_SUCCESS = "FETCH_COFFEE_SUCCESS";
export const FETCH_COFFEE_FAIL = "FETCH_COFFEE_FAIL";

export const ADD_TO_BASKET_START = "ADD_TO_BASKET_START";
export const ADD_TO_BASKET_SUCCESS = "ADD_TO_BASKET_SUCCESS";
export const ADD_TO_BASKET_FAIL = "ADD_TO_BASKET_FAIL";

export const REMOVE_FROM_BASKET_SUCCESS = "REMOVE_FROM_BASKET_SUCCESS";
