export const coffeeData = [
  {
    id: 1,
    name: "Caramak",
    strength: 4,
    taste: "Sweet",
    origin: "Cambodia",
    quanitity: 10,
    price: 2.8,
  },
  {
    id: 2,
    name: "Holliful",
    strength: 6,
    taste: "Woody",
    origin: "Kenya",
    quanitity: 10,
    price: 3.2,
  },
  {
    id: 3,
    name: "Shambo",
    strength: 9,
    taste: "Spicy",
    origin: "Mexico",
    quanitity: 5,
    price: 4.3,
  },
  {
    id: 4,
    name: "Flute",
    strength: 6,
    taste: "Floral",
    origin: "America",
    quanitity: 10,
    price: 2.9,
  },
  {
    id: 5,
    name: "Sugarbol",
    strength: 3,
    taste: "Sweet",
    origin: "Cambodia",
    quanitity: 10,
    price: 2.2,
  },
  {
    id: 6,
    name: "Vanillo",
    strength: 3,
    taste: "Sweet",
    origin: "America",
    quanitity: 10,
    price: 2.8,
  },
  {
    id: 7,
    name: "Strawbus",
    strength: 8,
    taste: "Spicy",
    origin: "Italy",
    quanitity: 5,
    price: 5.1,
  },
  {
    id: 8,
    name: "Darkzu",
    strength: 10,
    taste: "Woody",
    origin: "India",
    quanitity: 5,
    price: 4.8,
  },
  {
    id: 9,
    name: "Becup",
    strength: 5,
    taste: "Floral",
    origin: "India",
    quanitity: 10,
    price: 3.1,
  },
  {
    id: 10,
    name: "Pasayer",
    strength: 7,
    taste: "Spicy",
    origin: "Italy",
    quanitity: 10,
    price: 2.8,
  },
];
